version: "3.8"
services:
  movie-awards:
    build:
      context: .
    image:
      'movie-awards'
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - main

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
        - MYSQL_DATABASE=movie-awards
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
        - main

networks:
  main: