spring:
  datasource:
    url: jdbc:mysql://mysql:3306/movie-awards
    username: root
    passsword:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect