spring:
  datasource:
    url: jdbc:mysql://mysql:3306/movie_awards
    username: root
    passsword:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    user: root
    password:
    schemas: movie_awards
    url: jdbc:mysql://mysql:3306/
    locations: db.migration

movie-awards:
  omdb-api-url: http://www.omdbapi.com/
  omdb-api-key: 3e28ec88